In [11]:
#importer les packages necessaire
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [12]:
#importer les packages de machine learning
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, recall_score, accuracy_score, classification_report, precision_score

In [14]:
#charger le dataset
df = pd.read_excel('Copie de Coeur.xlsx')

In [16]:
#Travailler avec une copie du dataset pour éviter de le rechager en cas d'êrreur
df = df.copy()

In [17]:
#Afficher les informations relatives de mon dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   AGE          918 non-null    int64  
 1   SEXE         918 non-null    object 
 2   TDT          918 non-null    object 
 3   PAR          918 non-null    int64  
 4   CHOLESTEROL  918 non-null    int64  
 5   GAJ          918 non-null    int64  
 6   ECG          918 non-null    object 
 7   FCMAX        918 non-null    int64  
 8   ANGINE       918 non-null    object 
 9   DEPRESSION   918 non-null    float64
 10  PENTE        918 non-null    object 
 11  CŒUR         918 non-null    int64  
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB


In [18]:
#Standardisation des variables quantitatives
for col in df.drop('CŒUR', axis =1).select_dtypes(np.number).columns:
    df[col] = df[col]/df[col].max()

In [19]:
#Vérification des résultats du dataset
df.head()

AGE   SEXE  TDT   PAR  CHOLESTEROL  GAJ     ECG     FCMAX ANGINE  \
0  0.519481  homme   AA  0.70     0.479270  0.0  Normal  0.851485    Non   
1  0.636364  femme  DNA  0.80     0.298507  0.0  Normal  0.772277    Non   
2  0.480519  homme   AA  0.65     0.469320  0.0      ST  0.485149    Non   
3  0.623377  femme  ASY  0.69     0.354892  0.0  Normal  0.534653    Oui   
4  0.701299  homme  DNA  0.75     0.323383  0.0  Normal  0.603960    Non   

   DEPRESSION       PENTE  CŒUR  
0     0.000000  Ascendant     0  
1     0.161290       Plat     1  
2     0.000000  Ascendant     0  
3     0.241935       Plat     1  
4     0.000000  Ascendant     0

In [20]:
#Encodage des variables qualitatives du dataset
for col in df.select_dtypes('object').columns:
    df[col] = df[col].astype('category').cat.codes

In [21]:
#Vérification des résultats
df.head()

AGE  SEXE  TDT   PAR  CHOLESTEROL  GAJ  ECG     FCMAX  ANGINE  \
0  0.519481     1    0  0.70     0.479270  0.0    1  0.851485       0   
1  0.636364     0    3  0.80     0.298507  0.0    1  0.772277       0   
2  0.480519     1    0  0.65     0.469320  0.0    2  0.485149       0   
3  0.623377     0    1  0.69     0.354892  0.0    1  0.534653       1   
4  0.701299     1    3  0.75     0.323383  0.0    1  0.603960       0   

   DEPRESSION   PENTE  CŒUR  
0     0.000000      0     0  
1     0.161290      2     1  
2     0.000000      0     0  
3     0.241935      2     1  
4     0.000000      0     0

In [22]:
#Séparer la variable cible (coeur) et les variables explicatives
y = df['CŒUR']
x = df.drop('CŒUR', axis = 1)

In [23]:
#preparation des donnees de test et des donnees d'entrainememnt
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size =0.2, random_state =1)

In [24]:
#Vérifier le résultat
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(734, 11) (184, 11) (734,) (184,)


In [25]:
#Création d'un objet lr de la classe LogisticRegression
lr = LogisticRegression(solver ='newton-cg', random_state =1)

In [26]:
#Apprentissage du modèle
model = lr.fit(x_train, y_train)

In [27]:
#Probabilité d'appartenance à l'une des classes
predict_proba = model.predict_proba(x_test)
predict_proba[:5,:]

array([[0.39560595, 0.60439405],
       [0.18843348, 0.81156652],
       [0.04970935, 0.95029065],
       [0.09007617, 0.90992383],
       [0.28158313, 0.71841687]])

In [28]:
#Application du modèle au données de test
y_pred = model.predict(x_test)
y_pred[:5]

array([1, 1, 1, 1, 1])

In [29]:
#matrice de confusion
mc = confusion_matrix(y_test, y_pred)
mc

array([[ 66,   8],
       [  6, 104]])

In [30]:
#Taux de bonnes prédictions
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9239130434782609

In [31]:
#Sensibilité
recall = recall_score(y_test, y_pred)
recall

0.9454545454545454

In [32]:
#Précision
precision = precision_score(y_test, y_pred)
precision

0.9285714285714286

In [33]:
#plus de détails avec classification report
cr = classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.92      0.89      0.90        74
           1       0.93      0.95      0.94       110

    accuracy                           0.92       184
   macro avg       0.92      0.92      0.92       184
weighted avg       0.92      0.92      0.92       184



In [34]:
#Modèle Trival
df['CŒUR'].value_counts()/df.shape[0]

1    0.553377
0    0.446623
Name: CŒUR, dtype: float64

In [35]:
#Score d'entrainement (le taux de bonne prédiction calculé sur la base des données d'entrainement)
model.score(x_train, y_train)

0.8433242506811989

In [36]:
#Score d'entrainement (le taux de bonne prédiction calculé sur la base des données de test)
model.score(x_test, y_test)

0.9239130434782609